name = "cart-template"
client_id = "664cf222a9563d26ddcab74ea2765e50"
application_url = "https://web-production-e0416.up.railway.app"
embedded = true

[build]
  automatically_update_urls_on_dev = true
  dev_store_url = ""
  include_config_on_deploy = true

[access_scopes]
  # Learn more at https://shopify.dev/docs/apps/tools/cli/configuration
  scopes = "read_products,write_draft_orders,read_draft_orders,read_customers,write_customers"

[auth]
  redirect_urls = [
    "https://web-production-e0416.up.railway.app/auth/callback",
    "https://web-production-e0416.up.railway.app/auth/shopify/callback",
    "https://web-production-e0416.up.railway.app/api/auth/callback"
  ]

[webhooks]
  api_version = "2025-01"

  [[webhooks.subscriptions]]
    topics = ["app/uninstalled"]
    uri = "/webhooks"

[pos]
  embedded = false
